### ISSUE TITLE
[Feature request]: add config option to count only outgoing traffic

### ISSUE THREAD

**Issue by dartraiden** [mkorthof/traflimit#2]
It will be extremely useful for Oracle Cloud where inbound traffic is totally free
```
Inbound Data Transfer     Free
Outbound Data Transfer - Originating in North America, Europe, and UK - First 10 TB / Month	     Free
```
https://www.oracle.com/cloud/networking/pricing/

**Comment by mkorthof** [comment]
Change:
https://github.com/mkorthof/traflimit/blob/13272d1637b5a3f481a4619890856cb62c839046/traflimit.sh#L129

To just:
`TOTUSAGE="$OUTGOING"`
